# Temporarily using same model for all 3 tiers. will update later its just for testing
model_list:
  - model_name: tier1
    litellm_params:
      # 500 Requests per day - Perfect for fast utility tasks
      model: gemini/gemini-3.1-flash-lite
      api_key: os.environ/GEMINI_API_KEY

  - model_name: tier1
    litellm_params:
      model: gemini/gemini-3.1-flash-lite
      api_key: os.environ/GEMINI_API_KEY_2


  - model_name: tier2
    litellm_params:
      model: gemini/gemini-3.1-flash-lite
      # model: gemini/gemma-4-26b-a4b-it
      api_key: os.environ/GEMINI_API_KEY
      rpm: 15
  
  - model_name: tier2
    litellm_params:
      model: gemini/gemini-3.1-flash-lite
      # model: gemini/gemma-4-26b-a4b-it
      api_key: os.environ/GEMINI_API_KEY_2
      rpm: 15

  - model_name: tier3
    litellm_params:
      model: gemini/gemini-3.1-flash-lite
      api_key: os.environ/GEMINI_API_KEY
      rpm: 15
  
  - model_name: tier3
    litellm_params:
      model: gemini/gemini-3.1-flash-lite
      api_key: os.environ/GEMINI_API_KEY_2
      rpm: 15

  - model_name: gemini/text-embedding-004
    litellm_params:
      model: gemini/text-embedding-004
      api_key: os.environ/GEMINI_API_KEY
  
  - model_name: gemini/text-embedding-004
    litellm_params:
      model: gemini/text-embedding-004
      api_key: os.environ/GEMINI_API_KEY_2

general_settings:
  disable_device_logging: true
  disable_write_to_db: true
  success_callback: []
  failure_callback: []