model_list:
  - model_name: tier1
    litellm_params:
      model: ollama/phi:latest
      # model: ollama/qwen2.5:3b
      api_base: http://localhost:11434

  - model_name: tier2
    litellm_params:
      model: ollama/llama3:latest
      # model: ollama/mistral:latest
      api_base: http://localhost:11434

  - model_name: tier3
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY